#!/usr/bin/env bash
# Write a Bash script that displays:
#  The content of the current directory
#  In a list format
#  Where only the part of the name after the first dash is displayed (refer to the example)

stuff=0

list=$(ls)

for stuff in $list
do
	echo "$stuff" | cut -d "-" -f2
done
